"""Add image_url to articles

Revision ID: 2c6c05dd690a
Revises: abd38ccde0b4
Create Date: 2026-01-16 02:34:49.297965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6c05dd690a'
down_revision: Union[str, Sequence[str], None] = 'abd38ccde0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('categories', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.add_column('delete_articles', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete_articles', 'image_url')
    op.drop_constraint(None, 'categories', type_='unique')
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'image_url')
    # ### end Alembic commands ###
