"""add_fulltext_search_fix

Revision ID: 5ed8d1ac8f97
Revises: 2c6c05dd690a
Create Date: 2026-01-17 01:25:55.499918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ed8d1ac8f97'
down_revision: Union[str, Sequence[str], None] = '2c6c05dd690a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('ts_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', title || ' ' || content)", persisted=True), nullable=True))
    op.create_index('ix_articles_ts_vector', 'articles', ['ts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_ts_vector', table_name='articles', postgresql_using='gin')
    op.drop_column('articles', 'ts_vector')
    # ### end Alembic commands ###
