"""add_categories_final_fix

Revision ID: 68cfb9ca9b9c
Revises: 6c90cf0da1e1
Create Date: 2026-01-15 03:33:04.734435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cfb9ca9b9c'
down_revision: Union[str, Sequence[str], None] = '6c90cf0da1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
