"""add owner_id to articles table

Revision ID: 8ae45c8ddb8a
Revises: 4bc07e422876
Create Date: 2026-01-12 22:07:38.928414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae45c8ddb8a'
down_revision: Union[str, Sequence[str], None] = '4bc07e422876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'owner_id')
    # ### end Alembic commands ###
