"""add_delete_articles_table

Revision ID: abd38ccde0b4
Revises: 68cfb9ca9b9c
Create Date: 2026-01-15 13:15:18.824425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd38ccde0b4'
down_revision: Union[str, Sequence[str], None] = '68cfb9ca9b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delete_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delete_articles')
    # ### end Alembic commands ###
